import { Document, HeadingLevel, Paragraph, Table, TableCell, TableRow, TextRun, WidthType, ImageRun } from 'docx'
import { downloadWordDocx, parseDataUri } from './docxExport'

type Row = Record<string, unknown>
interface Point { id?: string; text?: string; image?: string; response?: string }

const s = (v: unknown): string => String(v ?? '')
const esc = (s: unknown): string => String(s ?? '').replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;')
const ml = (s: unknown): string => esc(s).replace(/\n/g, '<br/>')
const isLegacy = (r: Row): boolean => !Array.isArray(r.points)
const pointsOf = (r: Row): Point[] => (Array.isArray(r.points) ? (r.points as Point[]) : [])

function download(filename: string, blob: Blob): void {
  const url = URL.createObjectURL(blob)
  const a = document.createElement('a')
  a.href = url; a.download = filename
  document.body.appendChild(a); a.click(); a.remove()
  setTimeout(() => URL.revokeObjectURL(url), 1500)
}

// One RFI/Query rendered as a heading + a points table (S.No · Points · Image · Response).
function rfiBlock(r: Row): string {
  const num = esc(r.rfi_number || r.subject || '—')
  const kind = esc(r.kind || 'RFI')
  const disc = esc(r.discipline || '')
  const status = esc(r.status || (isLegacy(r) ? '' : 'Open'))
  const date = esc(r.submitted_date || '')
  const meta = [kind, disc, status, date].filter(Boolean).join(' · ')
  const head = `<h2 class="rfi-h">${num}${meta ? ` — ${meta}` : ''}</h2>`

  if (isLegacy(r)) {
    const rows = [
      r.subject ? `<tr><th>Subject</th><td>${esc(r.subject)}</td></tr>` : '',
      r.description ? `<tr><th>Description</th><td>${ml(r.description)}</td></tr>` : '',
      r.response ? `<tr><th>Response</th><td>${ml(r.response)}</td></tr>` : ''
    ].join('')
    return head + (rows ? `<table class="rfi-t"><tbody>${rows}</tbody></table>` : '<p class="rfi-empty">No detail.</p>')
  }

  const pts = pointsOf(r)
  if (!pts.length) return head + '<p class="rfi-empty">No points.</p>'
  const body = pts.map((p, i) => `<tr>
    <td class="c-no">${i + 1}</td>
    <td>${ml(p.text)}</td>
    <td class="c-img">${p.image ? `<img src="${p.image}" alt=""/>` : ''}</td>
    <td>${ml(p.response)}</td>
  </tr>`).join('')
  return head + `<table class="rfi-t"><thead><tr><th class="c-no">S. No.</th><th>Points</th><th class="c-img">Image</th><th>Response</th></tr></thead><tbody>${body}</tbody></table>`
}

const WORD_CSS = `
body{font-family:Calibri,'Segoe UI',Arial,sans-serif;font-size:11pt;color:#1a1a1a}
h1{font-size:18pt;color:#c0392b;margin:0 0 4pt;border-bottom:2px solid #c0392b;padding-bottom:4pt}
.rfi-sub{color:#666;font-size:10pt;margin:0 0 14pt}
.rfi-h{font-size:13pt;margin:16pt 0 6pt;color:#111}
.rfi-t{width:100%;border-collapse:collapse;margin:0 0 8pt}
.rfi-t th,.rfi-t td{border:1px solid #b9b9b9;padding:5pt 7pt;vertical-align:top;text-align:left;font-size:10.5pt}
.rfi-t thead th{background:#f1f2f4}
.rfi-t .c-no{width:44pt;text-align:center}
.rfi-t .c-img{width:170pt}
.rfi-t .c-img img{max-width:160pt;max-height:120pt}
.rfi-empty{color:#888;font-style:italic;margin:2pt 0 10pt}
`

export async function exportRfiWord(rows: Row[], projectName: string, fileName: string): Promise<void> {
  const children: Paragraph[] = []
  children.push(new Paragraph({ heading: HeadingLevel.TITLE, children: [new TextRun({ text: `RFI / Query Log — ${projectName || 'Project'}`, bold: true, size: 28 })] }))
  children.push(new Paragraph({ spacing: { after: 200 }, children: [new TextRun({ text: `${rows.length} item${rows.length === 1 ? '' : 's'} · generated by TOS Tracker`, italics: true })] }))

  rows.forEach((r, index) => {
    const num = esc(r.rfi_number || r.subject || '—')
    const kind = esc(r.kind || 'RFI')
    const disc = esc(r.discipline || '')
    const status = esc(r.status || (isLegacy(r) ? '' : 'Open'))
    const date = esc(r.submitted_date || '')
    const meta = [kind, disc, status, date].filter(Boolean).join(' · ')

    children.push(new Paragraph({ heading: HeadingLevel.HEADING_2, spacing: { before: index === 0 ? 0 : 240, after: 120 }, children: [new TextRun({ text: num, bold: true, size: 24 })] }))
    if (meta) children.push(new Paragraph({ spacing: { after: 120 }, children: [new TextRun({ text: meta, italics: true })] }))

    if (isLegacy(r)) {
      const body: TableCell[] = []
      if (r.subject) body.push(new TableCell({ children: [new Paragraph({ children: [new TextRun({ text: 'Subject' })] })] }))
      if (r.description) body.push(new TableCell({ children: [new Paragraph({ children: [new TextRun({ text: String(r.description) })] })] }))
      if (r.response) body.push(new TableCell({ children: [new Paragraph({ children: [new TextRun({ text: String(r.response) })] })] }))
      if (body.length) {
        children.push(new Paragraph())
        children.push(new Table({ rows: [new TableRow({ children: body })] }))
      }
      return
    }

    const pts = pointsOf(r)
    if (!pts.length) {
      children.push(new Paragraph({ spacing: { after: 120 }, children: [new TextRun({ text: 'No points.', italics: true })] }))
      return
    }

    pts.forEach((p, i) => {
      const rowsTable = new Table({
        rows: [
          new TableRow({ children: [
            new TableCell({ width: { size: 10, type: WidthType.PERCENTAGE }, children: [new Paragraph({ children: [new TextRun({ text: `Point ${i + 1}` })] })] }),
            new TableCell({ width: { size: 50, type: WidthType.PERCENTAGE }, children: [new Paragraph({ children: [new TextRun({ text: String(p.text || '') })] })] }),
            new TableCell({ width: { size: 20, type: WidthType.PERCENTAGE }, children: [new Paragraph({ children: [new TextRun({ text: p.image ? 'Image' : '' })] })] }),
            new TableCell({ width: { size: 20, type: WidthType.PERCENTAGE }, children: [new Paragraph({ children: [new TextRun({ text: String(p.response || '') })] })] }),
          ]})
        ]
      })
      children.push(new Paragraph({ spacing: { after: 120 } }))
      children.push(rowsTable)
      if (p.image) {
        const img = parseDataUri(p.image)
        children.push(new Paragraph({ spacing: { before: 120, after: 120 }, children: [new TextRun({ text: 'Attached image', bold: true })] }))
        children.push(new Paragraph({ children: [new ImageRun({ data: img?.data || new Uint8Array(), transformation: { width: 400, height: 250 }, type: img?.type || 'png' })] }))
      }
    })
  })

  // const doc = new Document({ sections: [{ properties: { page: { margin: { top: 1440, right: 1440, bottom: 1440, left: 1440 } } } }, children }] })
     const doc = new Document({
  sections: [
    {
      properties: {
        page: {
          margin: {
            top: 1440,
            right: 1440,
            bottom: 1440,
            left: 1440,
          },
        },
      },
      children,
    },
  ],
})
  await downloadWordDocx(fileName, doc)
}

// ── PowerPoint (.pptx) — a clean per-point deck via pptxgenjs (lazy-loaded) ────
export async function exportRfiPpt(rows: Row[], projectName: string, fileName: string): Promise<void> {
  const PptxGenJS = (await import('pptxgenjs')).default
  const pptx = new PptxGenJS()
  pptx.layout = 'LAYOUT_WIDE' // 13.33in × 7.5in (16:9)
  const RED = 'C0392B', GREEN = '1D9E75', DARK = '111111', MUTE = '888888'

  // Title slide
  const title = pptx.addSlide()
  title.addText('RFI / Query Log', { x: 0.6, y: 2.4, w: 12.1, h: 1, fontSize: 40, bold: true, color: RED })
  title.addText(projectName || '', { x: 0.6, y: 3.5, w: 12.1, h: 0.6, fontSize: 22, color: '333333' })
  title.addText(`${rows.length} item${rows.length === 1 ? '' : 's'} · generated by TOS Tracker`, { x: 0.6, y: 4.2, w: 12.1, h: 0.4, fontSize: 13, color: MUTE })

  for (const r of rows) {
    const num = s(r.rfi_number || r.subject || '—')
    const meta = [s(r.kind || 'RFI'), s(r.discipline), s(r.status || (isLegacy(r) ? '' : 'Open')), s(r.submitted_date)].filter(Boolean).join(' · ')

    if (isLegacy(r)) {
      const sl = pptx.addSlide()
      sl.addText(num, { x: 0.5, y: 0.3, w: 12.3, h: 0.6, fontSize: 24, bold: true, color: DARK })
      sl.addText(meta, { x: 0.5, y: 0.95, w: 12.3, h: 0.35, fontSize: 12, color: MUTE })
      sl.addText([{ text: 'Subject: ', options: { bold: true } }, { text: s(r.subject) }], { x: 0.5, y: 1.5, w: 12.3, h: 1, fontSize: 15, color: '222222', valign: 'top' })
      sl.addText([{ text: 'Description: ', options: { bold: true } }, { text: s(r.description) }], { x: 0.5, y: 2.6, w: 12.3, h: 2, fontSize: 14, color: '333333', valign: 'top' })
      sl.addText([{ text: 'Response: ', options: { bold: true, color: GREEN } }, { text: s(r.response) || '—' }], { x: 0.5, y: 4.8, w: 12.3, h: 2, fontSize: 14, color: '333333', valign: 'top' })
      continue
    }

    const pts = pointsOf(r)
    if (!pts.length) {
      const sl = pptx.addSlide()
      sl.addText(num, { x: 0.5, y: 0.3, w: 12.3, h: 0.6, fontSize: 24, bold: true, color: DARK })
      sl.addText(meta, { x: 0.5, y: 0.95, w: 12.3, h: 0.35, fontSize: 12, color: MUTE })
      sl.addText('No points.', { x: 0.5, y: 1.6, w: 12.3, h: 0.5, fontSize: 14, italic: true, color: MUTE })
      continue
    }

    // One slide per point (question + image + response) — clean & presentation-friendly.
    pts.forEach((p, i) => {
      const sl = pptx.addSlide()
      const hasImg = !!p.image
      const colW = hasImg ? 7.0 : 12.3
      sl.addText(`${num} — Point ${i + 1}/${pts.length}`, { x: 0.5, y: 0.3, w: 12.3, h: 0.5, fontSize: 22, bold: true, color: DARK })
      sl.addText(meta, { x: 0.5, y: 0.85, w: 12.3, h: 0.35, fontSize: 12, color: MUTE })
      sl.addText([{ text: 'Point: ', options: { bold: true, color: RED } }, { text: s(p.text) }], { x: 0.5, y: 1.4, w: colW, h: 2.6, fontSize: 15, color: '222222', valign: 'top' })
      sl.addText([{ text: 'Response: ', options: { bold: true, color: GREEN } }, { text: s(p.response) || '—' }], { x: 0.5, y: 4.2, w: colW, h: 2.6, fontSize: 14, color: '333333', valign: 'top' })
      if (hasImg) sl.addImage({ data: p.image, x: 7.8, y: 1.4, w: 5.0, h: 5.4, sizing: { type: 'contain', w: 5.0, h: 5.4 } })
    })
  }

  await pptx.writeFile({ fileName: `${fileName}.pptx` })
}
